### ISSUE TITLE
webpack build

### ISSUE THREAD

**Issue by yovanoc** [kekland/lapisdb#3] opened 2019-07-05 14:49 UTC
Hello I think is more a feature request than a bug but when I build my project in a bundle with webpack this give me this error, how could it be possible to achieve this? thanks a lot

<img width="1680" alt="Capture d’écran 2019-07-05 à 16 48 45" src="https://user-images.githubusercontent.com/7302317/60730188-d1534a80-9f44-11e9-8d83-89bc4b6726eb.png">

**Comment by kekland** [comment] 2019-07-05 15:10
Hi! Thanks for using LapisDB :)

It seems like an issue with Level. Does the database work when project is compiled without bundling?

**Comment by yovanoc** [comment] 2019-07-05 15:12
Yes, all is working great I love it, but I want a single .js file for the final product, and so, it seems to not find the .node binding in a node_modules folder, but I ask if there is a way to do something for that

**Comment by kekland** [comment] 2019-07-05 16:25
So, I've fixed this issue, but it is not a final solution yet.

The problem is with webpack setting the `__dirname` to `/`. To solve this issue, you have to add this into your webpack config:

```js
  node: {
      __dirname: false
  }
``` 

This will partially fix the issue, but now __dirname will be the directory where your bundle is in. But, because `node-gyp-build` searches for the bindings in __dirname, it will fail to find one if your bundle is in some other folder where no `package.json` is present (e.g. `dist`, `build`, etc). But, if your bundle file is in the same folder as `package.json` there are no issues.

To fix this, you have to search for your binding in `node_modules/leveldown/prebuilds`, in your case that is `node_modules/leveldown/prebuilds/darwin-x64/node.napi.node`. Then, you have to copy this file into `/build/Release/` folder in your build directory. So, for example, if your bundle is `./dist/app.bundle.js`, you have to put the bindings into `./dist/build/Release/`.

Hope this will solve this issue while I will search for a better solution :)

**Comment by yovanoc** [comment] 2019-07-05 20:49
mhh quite annoying while I just want a single final file :/ There is no way to not need this file?

**Comment by kekland** [comment] 2019-07-06 04:03
Yeah, this is a pain, but AFAIK, you can't bundle .node files into webpack builds. But, you can try building your app into the folder where your `package.json` is located, and it will automatically pick up the bindings from `node_modules`.

**Comment by yovanoc** [comment] 2019-07-06 07:53
Yeah I understand that but my boss tell me that we only want a single js file to launch on any machine with just nodejs installer aka: node bundle.js and we need an efficient local database management in therre :/

**Comment by kekland** [comment] 2019-07-06 08:05
Oh, okay. I am working on a lowdb adapter right now, it is a small json database, it might help you. I will update you on that.

**Comment by yovanoc** [comment] 2019-07-06 08:17
Your nice, thanks a lot !

**Comment by kekland** [comment] 2019-07-06 09:05
I've tested it with some basic tests, seems to be working, but make sure that it works on your production app too.

https://github.com/kekland/lapisdb-lowdb-adapter

**Comment by yovanoc** [comment] 2019-07-06 09:06
I will test that surely tomorrow and will come back to you, thanks ! 👍

**Comment by kekland** [comment] 2019-07-06 09:10
No problem :)

**Comment by yovanoc** [comment] 2019-07-06 12:59
<img width="492" alt="Capture d’écran 2019-07-06 à 14 58 21" src="https://user-images.githubusercontent.com/7302317/60756526-96ade880-9ffe-11e9-9852-7a3844e6491f.png">
<img width="479" alt="Capture d’écran 2019-07-06 à 14 58 30" src="https://user-images.githubusercontent.com/7302317/60756527-96ade880-9ffe-11e9-8947-8bde2b1a0fe5.png">

I got a "hang" problem and I don't know why

**Comment by kekland** [comment] 2019-07-06 13:24
Strange, everything seems to work fine in the example server

![image](https://user-images.githubusercontent.com/14993994/60756767-79d7dc00-a023-11e9-9673-d1af86f1def2.png)

Does your user has permission to ./database directory? And does the folder database exist in `appDataPath`?

**Comment by yovanoc** [comment] 2019-07-06 13:48
Ohhhh yes sorry I was thinking it would be created, all is working good with lowdb !

**Comment by kekland** [comment] 2019-07-06 14:00
Great! Happy to hear that it is working :)

Can I close this issue now?

**Comment by yovanoc** [comment] 2019-07-06 14:01
Yes! :)

**Closed** 2019-07-06 14:04 UTC
Labels: enhancement
